#!/bin/sh

readonly program="$(basename "$0")"

list() {
  filter="${1:-"/./"}"

  printf "token\tname\tartifact\n"
  brew cask list |
    awk "$filter" |
    xargs -I'{}' brew cask info '{}' --json=v1 |
    jq --raw-output --unbuffered \
      '[
        .[0].token,
        .[0].name,
        [.[0].artifacts[] | arrays, strings][0] |
          if type == "array" then
            .[0]
          elif type == "string" then
            split(" ")[0]
          else
            ""
          end
      ] | join("\t")'
}

usage() {
  echo "
    List cask artifacts.

    Usage:
      ${program} [options]

    Options:
      --app(s)            List only applications
      --font(s)           List only fonts
      --ql, --quicklook   List QuickLook plugins
      --colorpicker       List color pickers
      -h, --help          Show this help" |
    sed -E 's/^ {4}//'
}

for i in "$@"; do
  case $i in
  -h | --help)
    usage
    exit 0
    ;;
  --app | --apps)
    filter='!/^(font-|colorpicker-|quicklook-|ql)/'
    invert=1
    shift
    ;;
  --font | --fonts)
    filter='/^font-/'
    shift
    ;;
  --ql | --quicklook)
    filter='/^(quicklook-|ql)/'
    shift
    ;;
  --colorpicker)
    filter='/^colorpicker-/'
    shift
    ;;
  -*)
    echo "Unrecognised option: $1"
    exit 1
    ;;
  esac
done

list $filter $invert
